"use client";

import PrimaryButton from "@/components/ui/buttons/PrimaryButton";
import useModal from "@/hooks/useModal";
import showToast from "@/lib/toast";
import { Card, Input, Modal } from "antd";
import { AlertTriangle, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export default function TwoFactorAuthPage() {
  const { isModalOpen, handleCancelModal, handleShowModal } = useModal();

  const secretKey = "5FAH7Y5FTRZJF2FA";

  const copyToClipboard = async (text) => {
    try {
      navigator.clipboard.writeText(text);

      showToast.success("Copied Successfully");
    } catch (err) {
      console.error("Field to copy", err);
    }
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      {/* LEFT CARD */}
      <Card className="border rounded-xl " title="Two Factor Authenticator">
        {/* <h2 className="text-lg font-semibold mb-4">Two Factor Authenticator</h2> */}

        <label className="text-sm font-medium block mb-2">
          Two Factor Authenticator*
        </label>

        <div className="flex items-center mb-6 gap-2">
          <Input
            value={secretKey}
            readOnly
            size="large"
            className="rounded-r-none"
          />
          <PrimaryButton
            onClick={copyToClipboard}
            icon="Copy"
            iconClassName={"group-hover/primary-btn:scale-110 duration-200"}
          >
            <span>Copy</span>
          </PrimaryButton>
        </div>

        <div className="flex justify-center mb-6">
          <Image
            src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=2FA"
            alt="QR Code"
            width={160}
            height={160}
          />
        </div>

        <PrimaryButton onClick={handleShowModal} className="w-full">
          Enable
        </PrimaryButton>

        <Modal
          open={isModalOpen}
          onCancel={handleCancelModal}
          footer={false}
          closeIcon={false}
        >
          <div>
            <div className="mx-auto mb-4 flex h-20 w-20 border-red-500/50 border items-center justify-center rounded-full bg-red-100">
              <AlertTriangle className="text-red-500" size={50} />
            </div>

            <h2 className="text-center text-lg font-semibold text-neutral-900 ">
              Are you sure?
            </h2>

            <p className="mt-2 text-center text-sm text-gray-500">
              To Enable 2 factor authentication (Powered by google)?
            </p>

            {/* Actions */}
            <div className="mt-6 flex gap-2">
              <button
                //   onClick={onConfirm}
                className="w-full  py-2 bg-red-500! duration-300 rounded-lg text-white hover:bg-red-600! cursor-pointer "
              >
                Enable
              </button>

              <button
                onClick={handleCancelModal}
                className="w-full rounded-lg border border-gray-200 py-2  duration-300 text-sm font-medium text-gray-600 hover:bg-gray-50 cursor-pointer"
              >
                Cancel
              </button>
            </div>
          </div>
        </Modal>
      </Card>

      {/* RIGHT CARD */}
      <Card className="border rounded-xl" title="Google Authenticator">
        {/* <h2 className="text-lg font-semibold mb-4">Google Authenticator</h2> */}

        <h3 className="font-medium mb-2">Download Google Authenticator App</h3>

        <p className="text-sm text-gray-600 mb-6 leading-relaxed">
          Google Authenticator adds an extra layer of security to your online
          accounts by adding a second step of verification when you sign in.
          This means that in addition to your password, you'll also need to
          enter a code that is generated by the Google Authenticator app on your
          phone.{" "}
          <span className="text-primary-600 cursor-pointer ml-1">
            How to Setup?
          </span>
        </p>

        <div className="flex justify-center mb-6">
          <Image
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Google_Authenticator_%28April_2023%29.svg/500px-Google_Authenticator_%28April_2023%29.svg.png"
            alt="Google Authenticator"
            width={140}
            height={140}
          />
        </div>
        <Link
          href={
            "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&pcampaignid=web_share"
          }
          target="_blank"
        >
          {" "}
          <PrimaryButton className="w-full ">Download App</PrimaryButton>
        </Link>
      </Card>
    </div>
  );
}
