import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Geist, Geist_Mono } from "next/font/google";

import "./styles/globals.css";
import "./styles/antd.css";

import { ThemeProvider } from "@/contexts/ThemeContextProvider";
import { AuthProvider } from "@/contexts/AuthContextProvider";
import { ToastContainer } from "react-toastify";
import ReduxStoreProvider from "@/redux/provider/ReduxStoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Walletium | Dashboard Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1920px] mx-auto w-full shadow`}
      >
        <ReduxStoreProvider>
          {/* <AuthProvider> */}
          <AntdRegistry>
            <ThemeProvider>{children}</ThemeProvider>
            {/* React Toast Container */}
            <ToastContainer />
          </AntdRegistry>
          {/* </AuthProvider> */}
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
