import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Geist, Geist_Mono } from "next/font/google";

import "./styles/globals.css";
import "./styles/antd.css";

import { ThemeProvider } from "@/contexts/ThemeContextProvider";
import { ToastContainer } from "react-toastify";
import ReduxStoreProvider from "@/redux/provider/ReduxStoreProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Walletium | Dashboard Home",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  // REQUIRED FOR STATIC EXPORT:
  // This tells next-intl which locale to use for this static branch
  setRequestLocale(locale);

  // Fetch messages for this specific locale
  const messages = await getMessages();

  // Define which languages are Right-to-Left
  const isRTL = locale === "ar";

  return (
    <html lang={locale} dir={isRTL ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1920px] mx-auto w-full shadow`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ReduxStoreProvider>
            <AntdRegistry>
              <ThemeProvider>{children}</ThemeProvider>
              {/* React Toast Container */}
              <ToastContainer />
            </AntdRegistry>
          </ReduxStoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
